@Library('exmaple') _
pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.11-slim
    command:
    - cat
    tty: true
"""
        }
    }

    stages {
 

        stage('Run Python Script') {
            steps {
                container('python') {
                    example1(mohammad)
                    sh 'python3 --version'
                    sh 'python3 sources/add2vals.py 3 4'
                }
            }
        }

        stage('Run Tests') {
            steps {
                container('python') {
                    sh '''
                    pip install pytest || true
                    pytest -v || python3 sources/test_calc.py
                    '''
                }
            }
        }
    }
}
